# Q2 -- Material system. All triples whose subject is a MaterialSystem.

PREFIX mlips: <https://kg.ki.uni-stuttgart.de/_ontology/mlips#>

CONSTRUCT { ?s ?p ?o }
WHERE {
  ?s a mlips:MaterialSystem .
  ?s ?p ?o .
}
