# Q8 -- Hyperparameter settings.
# All triples whose subject is a HyperparameterSetting.

PREFIX mlips: <https://kg.ki.uni-stuttgart.de/_ontology/mlips#>

CONSTRUCT { ?s ?p ?o }
WHERE {
  ?s a mlips:HyperparameterSetting .
  ?s ?p ?o .
}
