# Dataset repo build pipeline.
#
# Targets:
#   make ontology         Regenerate mlips.{owl,ttl} from mlips.xhtml.
#   make roundtrip-check  Run check-roundtrip.sh on every paper in kg/papers/.
#   make listings         Run build-listings.sh on every paper.
#   make term-appendices  Generate the three term .tex files into dist/.
#   make figures          Render ontology figures into artifacts/figures/.
#   make release          ontology + roundtrip-check + listings + term-appendices + figures.
#   make darus            Package the DaRUS deposit zip into dist/darus/.
#   make clean            Remove generated outputs (keep canonical sources).

SAXON       ?= java -jar $(HOME)/bin/saxon-he.jar
RAPPER      ?= rapper
CONCON_ONTO ?= $(HOME)/code/software/concon-onto/code-repo/target/debug/concon-onto
EXTRACT_XSL ?= $(HOME)/code/software/concon-onto/code-repo/xslt/extract-owl.xsl

# Python toolchain. By default the pipeline runs in a local, gitignored
# .venv that `make` bootstraps from requirements.txt (see the `venv`
# target), so the Python build deps (rdflib, pyRdfa3) need no global
# install. To use an existing interpreter instead and skip the venv:
#   make ontology PY=python3 VENV_STAMP=
VENV        ?= .venv
PY          ?= $(VENV)/bin/python3
VENV_STAMP  ?= $(VENV)/.stamp

XHTML_SOURCE  = artifacts/ontology/mlips.source.xhtml
XHTML_PUBLISH = artifacts/ontology/mlips.xhtml
OWL_FILE     = artifacts/ontology/mlips.owl
TTL_FILE     = artifacts/ontology/mlips.ttl

DIST_SECTIONS = dist/sections
LATEX_SECTIONS = $(DIST_SECTIONS)/appendix-classes.tex \
                 $(DIST_SECTIONS)/appendix-object-properties.tex \
                 $(DIST_SECTIONS)/appendix-data-properties.tex

PAPERS = $(notdir $(basename $(wildcard artifacts/kg/papers/*.ttl)))

.PHONY: all release darus venv ontology xml-check roundtrip-check roundtrip-check-computed listings listings-computed term-appendices figures compute reason shacl cq cq-check clean

all: release

# === Release: produce all vendor-able outputs ===

release: ontology roundtrip-check listings term-appendices figures
	@echo
	@echo "Release ready. From the paper repo, run:"
	@echo "  make sync-from-dataset DATASET_PATH=$$(pwd)"

# === Python venv bootstrap ===
#
# `make` auto-creates a local .venv (gitignored) and installs the
# pipeline's Python dependencies the first time a Python step runs. The
# stamp file means this happens once, and again only when the requirements
# change. Installs from requirements.lock (exact, reproducible) when present,
# else falls back to requirements.txt. Run `make venv` to provision it.
venv: $(VENV_STAMP)

$(VENV)/.stamp: requirements.txt requirements.lock
	python3 -m venv $(VENV)
	$(VENV)/bin/pip install --quiet --upgrade pip
	@if [ -f requirements.lock ]; then \
	  echo "venv: installing pinned deps from requirements.lock" ; \
	  $(VENV)/bin/pip install --quiet -r requirements.lock ; \
	else \
	  echo "venv: requirements.lock absent, installing from requirements.txt" ; \
	  $(VENV)/bin/pip install --quiet -r requirements.txt ; \
	fi
	touch $@

# === Ontology pipeline (XHTML source -> XHTML published + OWL/TTL) ===
#
# The pipeline has two output paths from the source XHTML:
#
# A. Published XHTML (mlips.xhtml): the source XHTML with
#    deterministic enrichment -- a table of contents and per-class
#    Outgoing/Incoming property lists computed from the OWL/XML CDATA
#    blocks. Generated by enrich_xhtml.py. Served by the Axum server.
#
# B. OWL/TTL (mlips.{owl,ttl}): three-step build.
#      1. Saxon's extract-owl.xsl pulls term axioms out of the
#         <pre class="owl-xml"> CDATA blocks in the source XHTML.
#      2. rapper converts the resulting RDF/XML to Turtle.
#      3. merge_rdfa_into_owl.py adds the ontology-header annotations
#         that live as RDFa in the source XHTML (dcterms:title, ...,
#         owl:versionIRI, vann:preferredNamespace*, owl:imports,
#         dcterms:creator/contributor, dcterms:publisher, ...).
#
# Both outputs are derived from artifacts/ontology/mlips.source.xhtml
# (the only hand-edited file under artifacts/ontology/).

ontology: $(XHTML_PUBLISH) $(TTL_FILE)

$(XHTML_PUBLISH): $(XHTML_SOURCE) artifacts/scripts/enrich_xhtml.py artifacts/scripts/check_xml.py | $(VENV_STAMP)
	$(PY) artifacts/scripts/enrich_xhtml.py \
	  --source $(XHTML_SOURCE) --output $(XHTML_PUBLISH)
	@echo "Enriched $(XHTML_PUBLISH) (TOC + outgoing/incoming property lists)"
	$(PY) artifacts/scripts/check_xml.py $(XHTML_SOURCE) $(XHTML_PUBLISH)

# Standalone XML well-formedness guard (also run inside the ontology
# build above). The XHTML docs must be valid XML -- HTML-only named
# entities break browsers serving them as application/xhtml+xml.
xml-check: $(XHTML_PUBLISH) | $(VENV_STAMP)
	$(PY) artifacts/scripts/check_xml.py $(XHTML_SOURCE) $(XHTML_PUBLISH)

$(OWL_FILE): $(XHTML_SOURCE) artifacts/scripts/extract_owl.py | $(VENV_STAMP)
	@if [ -f "$(EXTRACT_XSL)" ]; then \
	  $(SAXON) -s:$(XHTML_SOURCE) -xsl:$(EXTRACT_XSL) -o:$(OWL_FILE) ; \
	else \
	  echo "Saxon XSL not found at $(EXTRACT_XSL); using Python fallback" ; \
	  $(PY) artifacts/scripts/extract_owl.py ; \
	fi
	@echo "Generated $(OWL_FILE) (term axioms only)"

$(TTL_FILE): $(OWL_FILE) artifacts/scripts/merge_rdfa_into_owl.py artifacts/scripts/extract_modules.py | $(VENV_STAMP)
	$(RAPPER) -i rdfxml -o turtle $(OWL_FILE) > $(TTL_FILE) 2>/dev/null
	$(PY) artifacts/scripts/merge_rdfa_into_owl.py --xhtml $(XHTML_SOURCE)
	@echo "Merged RDFa header annotations into $(TTL_FILE) and $(OWL_FILE)"
	$(PY) artifacts/scripts/extract_modules.py --xhtml $(XHTML_SOURCE)
	@echo "Added module annotations (rdfs:isDefinedBy) to $(TTL_FILE) and $(OWL_FILE)"

# === Round-trip check on every paper ===

roundtrip-check:
	@for p in $(PAPERS); do \
	  echo "==> $$p" ; \
	  ./artifacts/kg/check-roundtrip.sh "$$p" || exit 1 ; \
	done
	@echo "All $(words $(PAPERS)) papers round-trip cleanly (canonical, Q1-Q11)."

roundtrip-check-computed: compute
	@for p in $(PAPERS); do \
	  echo "==> $$p" ; \
	  ./artifacts/kg/check-roundtrip.sh --computed "$$p" || exit 1 ; \
	done
	@echo "All $(words $(PAPERS)) papers round-trip cleanly (computed, Q1-Q13)."

# === Per-paper Turtle-fragment listings ===

listings:
	@for p in $(PAPERS); do \
	  ./artifacts/kg/build-listings.sh "$$p" ; \
	done

listings-computed: compute
	@for p in $(PAPERS); do \
	  ./artifacts/kg/build-listings.sh --computed "$$p" ; \
	done

# === LaTeX term appendices into dist/sections/ ===

term-appendices: $(LATEX_SECTIONS)

$(LATEX_SECTIONS) &: $(TTL_FILE) | $(VENV_STAMP)
	@mkdir -p $(DIST_SECTIONS)
	$(PY) artifacts/scripts/generate_term_appendix.py \
	  --output-dir $(DIST_SECTIONS) \
	  --ontology $(TTL_FILE) \
	  --skip-skeletons

# === Figures rendered from the ontology ===

figures: $(TTL_FILE)
	./artifacts/tools/render_figures.sh

# === DaRUS deposit packaging ===
#
# One reproducible upload zip (git bundle of main + the release tag,
# README.md, LICENSE, and a generated CITATION.cff carrying the
# release commit SHA). The release tag v<version-from-CITATION.cff>
# must exist and point at HEAD. See artifacts/scripts/package_for_darus.py.

darus:
	python3 artifacts/scripts/package_for_darus.py

# === Computed-TTL pipeline (per-paper materialisation) ===
#
# For each paper, materialise the canonical paper.ttl plus the
# rdfs:label and inverse-role triples emitted by the two CONSTRUCTs
# under artifacts/kg/computed/. Output:
#   dist/artifacts/kg/papers/<paper-id>-computed.ttl
# These are not tracked (see .gitignore *-computed.ttl) and are
# regenerated on every `make compute`. The computed listings are
# what the paper appendix sources from (see paper-repo
# build-listings).

compute: $(TTL_FILE)
	@for p in $(PAPERS); do \
	  ./artifacts/kg/build-computed.sh "$$p" ; \
	done

# === Reasoner consistency check (ELK + HermiT via ROBOT) ===
#
# Runs both reasoners over mlips.owl and reports any unsatisfiable
# classes. ELK is fast and covers OWL 2 EL (which most of the
# ontology lives in); HermiT covers full OWL 2 DL and catches the
# axioms ELK can't reason about (existence axioms with non-EL
# fillers, cardinality restrictions, etc.). A green run is one of
# the gates listed in issue-0010 AC#6.
#
# Requires ROBOT (ontodev/robot, https://robot.obolibrary.org/).
# Drop robot.jar + the wrapper into ~/bin or anywhere on PATH.

ROBOT ?= robot

reason: $(OWL_FILE)
	@echo "==> ELK consistency"
	@if $(ROBOT) --input $(OWL_FILE) reason --reasoner ELK 2>&1 \
	     | grep -iE 'incon|unsat|error' ; then \
	  echo "ELK: FAIL" ; exit 1 ; \
	else \
	  echo "ELK: consistent, no unsatisfiable classes" ; \
	fi
	@echo "==> HermiT consistency"
	@if $(ROBOT) --input $(OWL_FILE) reason --reasoner hermit 2>&1 \
	     | grep -iE 'incon|unsat|error' ; then \
	  echo "HermiT: FAIL" ; exit 1 ; \
	else \
	  echo "HermiT: consistent, no unsatisfiable classes" ; \
	fi

# === OOPS! ontology pitfall scan (local, no web service) ===
#
# Bootstraps Apache Maven and the OOPS! source from
# github.com/oeg-upm/OOPS into ~/.cache/mlips-oops/, builds the
# OOPS! JAR, and runs it against artifacts/ontology/mlips.owl.
# Output: dist/oops-summary.tsv (per-pitfall counts) and
# dist/oops-report.txt (full log).
#
# OOPS! 0.3.0-SNAPSHOT only ports a subset of the published pitfall
# catalogue (P02-P08 in current revision); the full ~40-pitfall
# catalogue is only available via the public web UI.

oops: $(OWL_FILE)
	./artifacts/tools/oops-run.sh

# === SHACL validation (modularity enforcement) ===
#
# Validates artifacts/ontology/mlips.ttl against shapes/mlips-shapes.ttl
# with pyshacl (installed in the build venv). Conforms iff every mlips
# class/property is assigned to exactly one module (rdfs:isDefinedBy a
# https://w3id.org/mlips/module/* resource) -- the "enforced modules"
# R1 asked for. Non-zero exit on a violation.

SHAPES = shapes/mlips-shapes.ttl

shacl: $(TTL_FILE) $(SHAPES) | $(VENV_STAMP)
	$(PY) -m pyshacl -s $(SHAPES) -f human $(TTL_FILE)

# === Competency-question RDF -> .rq generation ===
#
# artifacts/kg/cq.ttl is the source of truth for the nine competency
# questions; cq-queries/cq<NN>.rq are generated from it (RDF is what
# concon's doc view renders; the .rq are derived for the round-trip
# harness and the paper appendix). `make cq` regenerates the .rq;
# `make cq-check` verifies they are byte-in-sync with cq.ttl (CI/release
# gate).
CQ_TTL = artifacts/kg/cq.ttl

cq: $(CQ_TTL) artifacts/scripts/gen_cq_queries.py | $(VENV_STAMP)
	$(PY) artifacts/scripts/gen_cq_queries.py
	@echo "Regenerated cq-queries/*.rq from $(CQ_TTL)"

cq-check: $(CQ_TTL) artifacts/scripts/gen_cq_queries.py | $(VENV_STAMP)
	$(PY) artifacts/scripts/gen_cq_queries.py --check

# === Clean ===

clean:
	rm -f $(OWL_FILE) $(TTL_FILE)
	rm -rf dist/
	rm -rf artifacts/kg/listings/
	rm -rf artifacts/figures/
