#!/usr/bin/env bash
#
# Materialise the *computed* TTL for one paper:
#
#   dist/artifacts/kg/papers/<paper-id>-computed.ttl
#     = canonical paper.ttl
#     + rdfs:label triples from artifacts/kg/computed/labels.rq
#     + inverse-role triples from artifacts/kg/computed/inverses.rq
#
# The labels CONSTRUCT joins paper-local instances with type-level
# entities defined in mlips.ttl + mlips-vocab.ttl, so those are
# concatenated into a transient input graph for that step. The
# inverses CONSTRUCT only needs the canonical paper.ttl.
#
# Outputs N-triples-style listings (oxigraph default for CONSTRUCT)
# but writes a single Turtle file by piping through `rapper -o turtle`.
#
# Usage:  artifacts/kg/build-computed.sh <paper-id>

set -euo pipefail

if [ -d "$HOME/.cargo/bin" ]; then
  case ":$PATH:" in
    *":$HOME/.cargo/bin:"*) ;;
    *) export PATH="$HOME/.cargo/bin:$PATH" ;;
  esac
fi

# Fall back to the repo-bundled shim (artifacts/tools/sparql) when no
# `sparql` CLI is installed: oxigraph_server when available, otherwise
# a pure-Python rdflib driver on the repo venv (see the shim's header).
if ! command -v sparql >/dev/null 2>&1; then
  export PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")/../tools" && pwd):$PATH"
fi

if [ $# -ne 1 ]; then
  echo "Usage: $0 <paper-id>" >&2
  exit 2
fi

PAPER_ID="$1"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
PAPER_TTL="$SCRIPT_DIR/papers/${PAPER_ID}.ttl"
ONTO_TTL="$REPO_ROOT/artifacts/ontology/mlips.ttl"
VOCAB_TTL="$SCRIPT_DIR/mlips-vocab.ttl"
LABELS_RQ="$SCRIPT_DIR/computed/labels.rq"
INVERSES_RQ="$SCRIPT_DIR/computed/inverses.rq"

OUT_DIR="$REPO_ROOT/dist/artifacts/kg/papers"
OUT_TTL="$OUT_DIR/${PAPER_ID}-computed.ttl"

if [ ! -f "$PAPER_TTL" ]; then
  echo "ERROR: not found: $PAPER_TTL" >&2
  exit 2
fi

mkdir -p "$OUT_DIR"

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

# Merged input graph for labels: ontology + vocab + paper.
MERGED="$WORK_DIR/merged.ttl"
cat "$ONTO_TTL" "$VOCAB_TTL" "$PAPER_TTL" > "$MERGED"

# Run the two CONSTRUCTs.
LABELS_NT="$WORK_DIR/labels.nt"
INVERSES_NT="$WORK_DIR/inverses.nt"

sparql "$LABELS_RQ" --graph "$MERGED" \
  | grep -E '^[[:space:]]*(<|_:|").*\.[[:space:]]*$' > "$LABELS_NT" || true
sparql "$INVERSES_RQ" --graph "$PAPER_TTL" \
  | grep -E '^[[:space:]]*(<|_:|").*\.[[:space:]]*$' > "$INVERSES_NT" || true

# Build the computed TTL: paper.ttl (in N-triples) + computed triples,
# canonicalised by rapper into pretty Turtle.
COMBINED_NT="$WORK_DIR/combined.nt"
{
  rapper -i turtle -o ntriples "$PAPER_TTL" 2>/dev/null
  cat "$LABELS_NT" "$INVERSES_NT"
} | sort -u > "$COMBINED_NT"

# Convert back to Turtle for the published artifact. To keep the
# output abbreviated (mlips:, rdfs:, entity:, ...), prepend the canonical
# paper's @prefix block before the n-triples and let rapper re-emit;
# rapper accepts a Turtle document whose body is full-IRI triples.
PREFIX_BLOCK=$(grep '^@prefix' "$PAPER_TTL" || true)
ABBREVIATED="$WORK_DIR/abbreviated.ttl"
{
  echo "$PREFIX_BLOCK"
  echo
  cat "$COMBINED_NT"
} | rapper -q -i turtle -o turtle - 'http://example.org/' 2>/dev/null \
  > "$ABBREVIATED"

{
  echo "# Computed Turtle for ${PAPER_ID}."
  echo "#"
  echo "# Materialisation of the canonical artifacts/kg/papers/${PAPER_ID}.ttl"
  echo "# plus the inverse-role and rdfs:label triples emitted by"
  echo "# artifacts/kg/computed/{inverses,labels}.rq. Regenerated by"
  echo "# 'make compute'; not tracked in git."
  echo
  cat "$ABBREVIATED"
} > "$OUT_TTL"

# Also persist the templated labels alone. concon (>= v0.2.0) owns the
# `computed` named graph and derives only axiom-expressible triples
# itself, so the templated labels are uploaded separately to the
# consumer-owned `labels` graph (see scripts/upload_to_concon.py).
LABELS_OUT="$OUT_DIR/${PAPER_ID}-labels.ttl"
LABELS_ABBREV="$WORK_DIR/labels-abbreviated.ttl"
{
  echo "$PREFIX_BLOCK"
  echo
  cat "$LABELS_NT"
} | rapper -q -i turtle -o turtle - 'http://example.org/' 2>/dev/null \
  > "$LABELS_ABBREV"

{
  echo "# Computed labels for ${PAPER_ID}."
  echo "#"
  echo "# The templated rdfs:label triples emitted for the canonical"
  echo "# artifacts/kg/papers/${PAPER_ID}.ttl by artifacts/kg/computed/labels.rq."
  echo "# Uploaded to the consumer-owned 'labels' named graph. Regenerated by"
  echo "# 'make compute'; not tracked in git."
  echo
  cat "$LABELS_ABBREV"
} > "$LABELS_OUT"

LABEL_COUNT=$(wc -l < "$LABELS_NT")
INVERSE_COUNT=$(wc -l < "$INVERSES_NT")
TOTAL=$(wc -l < "$COMBINED_NT")
echo "  ${PAPER_ID}: ${LABEL_COUNT} computed labels, ${INVERSE_COUNT} computed inverses, ${TOTAL} triples total -> ${OUT_TTL} (+ ${PAPER_ID}-labels.ttl)"
