#!/usr/bin/env python3
"""Validate mlips:sameAsWikidata targets by Wikidata type (make wikidata-check).

Merges the per-paper KGs + controlled vocabulary + the materialized
Wikidata type snapshot (artifacts/kg/wikidata-types.ttl) and validates
with shapes/wikidata-shapes.ttl (pyshacl). Writes the review queue to
artifacts/kg/wikidata-review.md: Violations (typed target reaches no
allowed class -- the wrong-QID signature) and Warnings (target has no
type statements on Wikidata; cannot be checked). Exit code 1 only on
Violations; Warnings are a non-blocking review queue.
"""

import glob
import re
import sys
from datetime import date
from pathlib import Path

from pyshacl import validate
from rdflib import Graph, Namespace

REPO = Path(__file__).resolve().parents[2]
SH = Namespace("http://www.w3.org/ns/shacl#")


def main():
    data = Graph()
    for f in glob.glob(str(REPO / "artifacts/kg/papers/*.ttl")):
        data.parse(f, format="turtle")
    data.parse(REPO / "artifacts/kg/mlips-vocab.ttl", format="turtle")
    snapshot = REPO / "artifacts/kg/wikidata-types.ttl"
    data.parse(snapshot, format="turtle")
    m = re.search(r"on (\d{4}-\d{2}-\d{2})", snapshot.read_text())
    snap_date = m.group(1) if m else "unknown"

    shapes = Graph()
    shapes.parse(REPO / "shapes/wikidata-shapes.ttl", format="turtle")

    conforms, report, _ = validate(data, shacl_graph=shapes, advanced=True)

    entries = []
    for r in report.subjects(SH.sourceShape, None):
        sev = report.value(r, SH.resultSeverity)
        focus = report.value(r, SH.focusNode)
        value = report.value(r, SH.value)
        msg = report.value(r, SH.resultMessage)
        entries.append((str(sev).split("#")[-1], str(focus), str(value), str(msg)))
    entries.sort()
    violations = [e for e in entries if e[0] == "Violation"]
    warnings = [e for e in entries if e[0] == "Warning"]

    n_links = len(list(data.subject_objects(
        Namespace("https://w3id.org/mlips#").sameAsWikidata)))

    out = [
        "# Wikidata cross-reference review queue\n\n",
        "Generated by `make wikidata-check` "
        "(artifacts/scripts/check_wikidata_types.py) against the type "
        "snapshot of **%s**.\n\n" % snap_date,
        "- `sameAsWikidata` link assertions checked: **%d**\n" % n_links,
        "- Wrong-type **violations: %d**\n" % len(violations),
        "- Unverifiable (untyped on Wikidata) **warnings: %d**\n\n" % len(warnings),
    ]
    if violations:
        out.append("## Violations (fix before release)\n\n")
        out.append("| subject | target | message |\n|---|---|---|\n")
        for _, f, v, msg in violations:
            out.append("| %s | %s | %s |\n" % (f, v, msg))
        out.append("\n")
    if warnings:
        out.append("## Review queue (cannot verify: no P31/P279 on Wikidata)\n\n")
        out.append("These links were verified manually by label at snapshot "
                   "time; they cannot be type-checked until someone adds type "
                   "statements upstream on Wikidata (it is CC0 -- adding P31 "
                   "there is the durable fix).\n\n")
        out.append("| subject | target | note |\n|---|---|---|\n")
        for _, f, v, _ in warnings:
            out.append("| %s | %s | untyped on Wikidata as of %s |\n"
                       % (f, v, snap_date))
        out.append("\n")
    if not violations and not warnings:
        out.append("All links pass. Queue empty.\n")
    (REPO / "artifacts/kg/wikidata-review.md").write_text("".join(out))

    print("checked %d links: %d violations, %d warnings -> "
          "artifacts/kg/wikidata-review.md"
          % (n_links, len(violations), len(warnings)))
    sys.exit(1 if violations else 0)


if __name__ == "__main__":
    main()
