#!/usr/bin/env python3
"""Materialize the Wikidata types of every mlips:sameAsWikidata target.

Deliberate, dated snapshot step (NOT per-build: Wikidata is
non-deterministic and rate-limited). For each target QID in the
per-paper KGs + the controlled vocabulary, fetches P31 (instance of)
plus a bounded P279 (subclass of) ancestry (default depth 8) and
English labels, via the wbgetentities API (batched, 50 ids/request),
and writes artifacts/kg/wikidata-types.ttl with fetch-date provenance.
QID redirects are resolved and additionally recorded as owl:sameAs so
the SHACL check can flag stale IRIs. Wikidata content is CC0; the
snapshot is re-served as the …/graph/wikidata named graph.

Usage: fetch_wikidata_types.py [--depth 8] [--out artifacts/kg/wikidata-types.ttl]
"""

import argparse
import glob
import json
import re
import time
import urllib.parse
import urllib.request
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
API = "https://www.wikidata.org/w/api.php"
UA = "onto-mlips-wikidata-typecheck/0.1 (https://w3id.org/mlips)"


def api_get(ids):
    q = urllib.parse.urlencode({
        "action": "wbgetentities", "ids": "|".join(ids),
        "props": "claims|labels|redirects", "languages": "en",
        "format": "json"})
    req = urllib.request.Request(API + "?" + q, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.load(r)


def claim_targets(entity, prop):
    out = []
    for c in entity.get("claims", {}).get(prop, []):
        try:
            out.append(c["mainsnak"]["datavalue"]["value"]["id"])
        except (KeyError, TypeError):
            pass
    return out


def collect_targets():
    qids = set()
    files = glob.glob(str(REPO / "artifacts/kg/papers/*.ttl"))
    files.append(str(REPO / "artifacts/kg/mlips-vocab.ttl"))
    for f in files:
        for m in re.finditer(r"wikidata\.org/entity/(Q\d+)", open(f).read()):
            qids.add(m.group(1))
    return sorted(qids, key=lambda q: int(q[1:]))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--depth", type=int, default=8)
    ap.add_argument("--out", default=str(REPO / "artifacts/kg/wikidata-types.ttl"))
    args = ap.parse_args()

    targets = collect_targets()
    print("targets:", len(targets))

    entities = {}          # qid -> {p31: [...], p279: [...], label: str}
    redirects = {}         # requested-qid -> actual-qid
    frontier = list(targets)
    depth = 0
    seen = set()
    while frontier and depth <= args.depth:
        batch_ids = [q for q in frontier if q not in entities]
        nxt = []
        for i in range(0, len(batch_ids), 50):
            chunk = batch_ids[i:i + 50]
            data = api_get(chunk)
            for qid, ent in data.get("entities", {}).items():
                if "redirects" in ent:
                    redirects[ent["redirects"]["from"]] = ent["redirects"]["to"]
                if "missing" in ent:
                    entities[qid] = None
                    continue
                real = ent["id"]
                if real != qid:
                    redirects[qid] = real
                rec = {
                    "p31": claim_targets(ent, "P31"),
                    "p279": claim_targets(ent, "P279"),
                    "label": ent.get("labels", {}).get("en", {}).get("value", ""),
                }
                entities[qid] = rec
                entities.setdefault(real, rec)
                for c in rec["p31"] + rec["p279"]:
                    if c not in entities and c not in seen:
                        seen.add(c)
                        nxt.append(c)
            time.sleep(0.5)
        # frontier for next depth: only P279 expansion after the first
        # level (P31 targets' own ancestry is what matters);
        # P31-of-classes is not traversed.
        frontier = nxt
        depth += 1
        print("depth", depth, "fetched", len(entities), "queued", len(frontier))

    today = date.today().isoformat()
    lines = [
        "# Wikidata type snapshot for mlips:sameAsWikidata targets.\n",
        "#\n",
        "# Generated by artifacts/scripts/fetch_wikidata_types.py on %s\n" % today,
        "# (%d target QIDs; P31 + P279 ancestry to depth %d; labels @en).\n"
        % (len(targets), args.depth),
        "# Wikidata content is CC0. Regenerate deliberately, not per-build;\n",
        "# served as the https://w3id.org/mlips/graph/wikidata named graph.\n",
        "\n",
        "@prefix wd:   <http://www.wikidata.org/entity/> .\n",
        "@prefix wdt:  <http://www.wikidata.org/prop/direct/> .\n",
        "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n",
        "@prefix owl:  <http://www.w3.org/2002/07/owl#> .\n",
        "@prefix dcterms: <http://purl.org/dc/terms/> .\n",
        "@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .\n",
        "\n",
        "<https://w3id.org/mlips/graph/wikidata> dcterms:created \"%s\"^^xsd:date ;\n" % today,
        "    dcterms:source <https://www.wikidata.org/> ;\n",
        "    dcterms:license <https://creativecommons.org/publicdomain/zero/1.0/> .\n",
        "\n",
    ]
    for old, new in sorted(redirects.items()):
        lines.append("wd:%s owl:sameAs wd:%s .  # REDIRECTED QID\n" % (old, new))
    missing = sorted(q for q, v in entities.items() if v is None)
    for q in missing:
        lines.append("# MISSING/DELETED entity: wd:%s\n" % q)
    for qid in sorted((q for q, v in entities.items() if v),
                      key=lambda q: int(q[1:])):
        rec = entities[qid]
        if rec["label"]:
            lines.append("wd:%s rdfs:label %s@en .\n"
                         % (qid, json.dumps(rec["label"])))
        for c in rec["p31"]:
            lines.append("wd:%s wdt:P31 wd:%s .\n" % (qid, c))
        for c in rec["p279"]:
            lines.append("wd:%s wdt:P279 wd:%s .\n" % (qid, c))
    Path(args.out).write_text("".join(lines))
    print("wrote %s (%d entities, %d redirects, %d missing)"
          % (args.out, len([v for v in entities.values() if v]),
             len(redirects), len(missing)))


if __name__ == "__main__":
    main()
