PREFIX mlips: <https://w3id.org/mlips#>

# CQ8: Which simulation types (molecular dynamics, Monte Carlo,
# geometry optimisation, phonon calculations, thermodynamic
# integration) have been performed with a given MLIP?

SELECT ?algo ?sim WHERE {
  ?algo a mlips:MLIPMethod ;
        mlips:supportsSimulation ?sim .
}
